export const country_mapping = {
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bi": "Burundi",
    "bj": "Benin",
    "bo": "Bolivia",
    "br": "Brazil",
    "bs": "Bahamas",
    "bt": "Bhutan",
    "bw": "Botswana",
    "by": "Belarus",
    "bz": "Belize",
    "ca": "Canada",
    "cd": "Democratic Republic of the Congo",
    "cf": "Central African Republic",
    "cg": "Congo",
    "ch": "Switzerland",
    "ci": "C\u00f4te d'Ivoire",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cy": "Cyprus",
    "de": "Germany",
    "dj": "Djibouti",
    "dk": "Denmark",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egypt",
    "eh": "Western Sahara",
    "er": "Eritrea",
    "es": "Spain",
    "et": "Ethiopia",
    "fi": "Finland",
    "fj": "Fiji",
    "fk": "Falkland Islands",
    "fr": "France",
    "ga": "Gabon",
    "gb": "United Kingdom",
    "ge": "Georgia",
    "gh": "Ghana",
    "gl": "Greenland",
    "gm": "Gambia",
    "gn": "Guinea",
    "gq": "Equatorial Guinea",
    "gr": "Greece",
    "gt": "Guatemala",
    "gw": "Guinea-Bissau",
    "gy": "Guyana",
    "hn": "Honduras",
    "hr": "Croatia",
    "ht": "Haiti",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "jm": "Jamaica",
    "jo": "Jordan",
    "jp": "Japan",
    "ke": "Kenya",
    "kg": "Kyrgyzstan",
    "kh": "Cambodia",
    "kp": "North Korea",
    "kr": "South Korea",
    "kw": "Kuwait",
    "kz": "Kazakhstan",
    "la": "Laos",
    "lb": "Lebanon",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "ls": "Lesotho",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "md": "Moldova",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mk": "North Macedonia",
    "ml": "Mali",
    "mm": "Myanmar",
    "mn": "Mongolia",
    "mr": "Mauritania",
    "mw": "Malawi",
    "mx": "Mexico",
    "my": "Malaysia",
    "mz": "Mozambique",
    "na": "Namibia",
    "nc": "New Caledonia",
    "ne": "Niger",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Netherlands",
    "no": "Norway",
    "np": "Nepal",
    "nz": "New Zealand",
    "om": "Oman",
    "pa": "Panama",
    "pe": "Peru",
    "pg": "Papua New Guinea",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "ps": "Palestine",
    "pt": "Portugal",
    "py": "Paraguay",
    "qa": "Qatar",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "rw": "Rwanda",
    "sa": "Saudi Arabia",
    "sb": "Solomon Islands",
    "sd": "Sudan",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sl": "Sierra Leone",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Suriname",
    "ss": "South Sudan",
    "sv": "El Salvador",
    "sy": "Syria",
    "sz": "Eswatini",
    "td": "Chad",
    "tf": "Fr. S. Antarctic Lands",
    "tg": "Togo",
    "th": "Thailand",
    "tj": "Tajikistan",
    "tl": "Timor-Leste",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tt": "Trinidad and Tobago",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "ug": "Uganda",
    "us": "United States of America",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "ve": "Venezuela",
    "vn": "Viet Nam",
    "vu": "Vanuatu",
    "ye": "Yemen",
    "za": "South Africa",
    "zm": "Zambia",
    "zw": "Zimbabwe",
    "mc": "Monaco",
    "bb": "Barbados",
    "bm": "Bermuda",
    "bh": "Bahrain",
    "ad": "Andorra",
    "as": "American Samoa",
    "ai": "Anguilla",
    "aw": "Aruba",
    "bq": "Bonaire, Sint Eustatius and Saba",
    "vg": "British Virgin Islands",
    "vi": "United States Virgin Islands",
    "ag": "Antigua and Barbuda",
    "pf": "French Polynesia",
    "va": "Holy See",
    "ky": "Cayman Islands",
    "bn": "Brunei Darussalam",
    "ck": "Cook Islands",
    "fo": "Faroe Islands",
    "im": "Isle of Man",
    "cw": "Cura\u00e7ao",
    "wf": "Wallis and Futuna Islands",
    "tv": "Tuvalu",
    "tc": "Turks and Caicos Islands",
    "to": "Tonga",
    "tk": "Tokelau",
    "sx": "Sint Maarten (Dutch part)",
    "sm": "San Marino",
    "ws": "Samoa",
    "pm": "Saint Pierre and Miquelon",
    "kn": "Saint Kitts and Nevis",
    "sh": "Saint Helena",
    "re": "R\u00e9union",
    "pw": "Palau",
    "mp": "Northern Mariana Islands",
    "nu": "Niue",
    "nr": "Nauru",
    "ms": "Montserrat",
    "fm": "Micronesia (Fed. States of)",
    "yt": "Mayotte",
    "mq": "Martinique",
    "mh": "Marshall Islands",
    "li": "Liechtenstein",
    "gu": "Guam",
    "gp": "Guadeloupe",
    "gd": "Grenada",
    "gi": "Gibraltar",
    "gf": "French Guiana",
    "ki": "Kiribati",
    "cv": "Cape Verde",
    "cz": "Czechia",
    "sc": "Seychelles",
    "dm": "Dominica",
    "km": "Comoros",
    "lc": "Saint Lucia",
    "mt": "Malta",
    "mu": "Mauritius",
    "mv": "Maldives",
    "st": "Sao Tome and Principe",
    "vc": "Saint Vincent and the Grenadines",
    "hk": "Hong Kong",
    "mo": "Macao"
};